### ISSUE TITLE
Day 3 - Spotify Artist API - make the call work, page populate

### ISSUE THREAD

**Issue by lsammons** [lsammons/spotavinyl#11]
Get API to return a user's artist data. 
Goal: top 10 artists by listening frequency.

**Comment by lsammons** [comment]
Maddie and Joe are both working on this together.

**Comment by jdar22169** [comment]
The API call works, but we need to move it from the SPOTIFY tutorial to our code.

**Comment by jdar22169** [comment]
I'm closing this issue because I completed it in 9. The template and the Spotify API call went hand in hand.

**Comment by jdar22169** [comment]
I'm closing this issue because I completed it 9. I worked on the handlebars template for spotify and the spotify API call at the same time.
