### ISSUE TITLE
Day 3 - Code Handlebars template for Spotify data on index.html

### ISSUE THREAD

**Issue by lsammons** [lsammons/spotavinyl#9]
Display:  Artist name, Artist image.

**Comment by jdar22169** [comment]
The data will populate the page, but the code just needs to be cleaned up.

**Comment by jdar22169** [comment]
The data is populating the page, and I deleted the placeholders for the carousel. I cannot get the data to be place horizontally.

**Comment by lsammons** [comment]
Maddie fixed the data so that it now populates horizontally.  All artist data is now on page -- Done!
